name: Show secret
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar secret
        run: "El secret: echo ${{ secrets.TEST_SECRET }}"         