name: Show secret
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar secret
        run: |
          echo "El secret: ${{ secrets.TEST_SECRET }}"
          echo "El autor del commit es ${{ github.actor }}"     