name: Show secret
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VARIABLE_ENTORNO: 0.145.0
    steps:
      - name: Mostrar secret
        run: |
          echo "Un secret creado en el repositorio: ${{ secrets.TEST_SECRET }}" 
          echo "Variables de Github (autor del commit es) ${{ github.actor }}"
          echo "La VARIABLE_ENTORNO declarada en este archivo es: ${VARIABLE_ENTORNO}"   
      - name: Login in docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.TOKEN_USERNAME_DOCKERHUB }}
          password: ${{ secrets.TOKEN_WORKFLOW_DOCKERHUB }}  

